구글 드라이브 불러오기

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Arrays of Data



#### Arrays with Python Lists

In [3]:
v = [0.5, 0.75, 1.0, 1.5, 2.0] # list

In [4]:
m = [v, v, v]
m

[[0.5, 0.75, 1.6, 1.5, 2.0],
 [0.5, 0.75, 1.6, 1.5, 2.0],
 [0.5, 0.75, 1.6, 1.5, 2.0]]

In [5]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [10]:
m[1][0]

0.5

In [11]:
v1 = [0.5, 1.5]
v2 = [1,2]
m = [v1, v2]
c = [m, m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [12]:
c[1][1][0]

1

In [13]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [14]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [15]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 *[deepcopy(v), ]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [16]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

#### The Python array *Class*

In [17]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [19]:
import array

In [22]:
a = array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [24]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 0.5])

In [25]:
a.extend([5.0, 6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 0.5, 5.0, 6.75])

In [26]:
2*a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 0.5, 5.0, 6.75])

In [28]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 0.5, 5.0, 6.75]

In [29]:
f = open('array.apy', 'wb')
a.tofile(f)
f.close()

In [30]:
with open('array.apy', 'wb') as f:
    a.tofile(f)

### Regular NumPy Arrays



#### The Basics

In [36]:
import numpy as np

In [37]:
a=np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [38]:
type(a)

numpy.ndarray

In [39]:
a = np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [40]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
a = np.arange(8, dtype=np.float)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [42]:
a[5:]

array([5., 6., 7.])

In [43]:
a[:2]

array([0., 1.])

In [44]:
a.sum()

28.0

In [45]:
a.std()

2.29128784747792

In [46]:
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [50]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [51]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [52]:
2 * a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [55]:
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [56]:
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [54]:
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [57]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [58]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [59]:
np.sqrt(2.5)

1.5811388300841898

In [60]:
import math

In [61]:
math.sqrt(2.5)

1.5811388300841898

#### Multiple Dimensions

In [64]:
b = np.array([a, a*2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [65]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [66]:
b[0,2]

2.0

In [67]:
b[:, 1]

array([1., 2.])

In [68]:
b.sum()

84.0

In [69]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [70]:
b.sum(axis=1)

array([28., 56.])

In [71]:
# ndarray objects
c = np.zeros((2,3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [72]:
c = np.ones((2,3,4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [73]:
d = np.zeros_like(c, dtype='f16', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [74]:
d = np.ones_like(c, dtype='f16', order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

In [75]:
e = np.empty((2, 3, 2))
e

array([[[3.96361279e-316, 2.61854792e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.91749408e-310, 1.50008929e+248]],

       [[4.50620083e-144, 2.78225500e+296],
        [1.43267083e+161, 4.56317366e-144],
        [2.77618871e+184, 2.66090405e-312]]])

In [76]:
f = np.empty_like(c)
f

array([[[  80224416,          0,         53,          0],
        [         0,          0,          0,          0],
        [         0,      32599, 1953702523, 1937077345]],

       [[1864514082,  573317739, 1635017060, 2105227810],
        [1701650988, 1633968500,  975331700,  573341051],
        [1853189990, 1715085924, 1702063201,        125]]], dtype=int32)

In [77]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
g = np.linspace(5, 15, 12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

#### Metainformation

In [79]:
g.size

12

In [80]:
g.itemsize

8

In [81]:
g.ndim

1

In [82]:
g.shape

(12,)

In [83]:
g.dtype

dtype('float64')

In [84]:
g.nbytes

96

#### Reshaping and Resizing

In [85]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
g.shape

(15,)

In [88]:
np.shape(g)

(15,)

In [89]:
g.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
h = g.reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [91]:
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [92]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [93]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [94]:
np.hstack((h, 2 * h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [95]:
np.vstack((h, 0.5 * h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [96]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [97]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
h.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [99]:
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [100]:
for i in h.flat:
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [101]:
for i in h.ravel(order='C'):
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [102]:
for i in h.ravel(order='F'):
    print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

#### Boolean Arrays

In [103]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [104]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [105]:
h <= 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [106]:
h == 5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [107]:
(h == 5).astype(int) #True는 0, False는 0으로 표현

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [108]:
(h > 4) & (h <= 12) # &:and

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [109]:
h[h>8]

array([ 9, 10, 11, 12, 13, 14])

In [110]:
h[(h > 4) & (h <= 12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
h[(h < 4) | (h >= 12)] # | : or

array([ 0,  1,  2,  3, 12, 13, 14])

In [116]:
np.where(h > 7, 1, 0) # array h 에서 7이상이면 1, 아니면 0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [113]:
np.where(h % 2 == 0, 'even', 'odd')

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [114]:
np.where(h <= 7, h * 2, h / 2)

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

#### Speed Comparison

In [117]:
import random
I = 5000

In [118]:
%time mat = [[random.gauss(0, 1) for j in range(I)] \
             for i in range(I)]

CPU times: user 15.2 s, sys: 699 ms, total: 15.9 s
Wall time: 16 s


In [119]:
mat[0][:5]

[1.5602879753880734,
 -1.4254445181056459,
 -1.0523645349685855,
 -0.014067710828187325,
 -0.5327760183242733]

In [120]:
%time sum([sum(l) for l in mat])

CPU times: user 156 ms, sys: 1.92 ms, total: 158 ms
Wall time: 159 ms


2139.1563464769556

In [121]:
import sys
sum([sys.getsizeof(l) for l in mat])

215200000

In [122]:
%time mat = np.random.standard_normal((I, I))

CPU times: user 1.31 s, sys: 171 ms, total: 1.48 s
Wall time: 1.48 s


In [123]:
%time mat.sum()

CPU times: user 21.9 ms, sys: 0 ns, total: 21.9 ms
Wall time: 24.1 ms


-6748.405169847809

In [124]:
mat.nbytes

200000000

In [125]:
sys.getsizeof(mat)

200000112

### Structured NumPy Arrays

In [126]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [127]:
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'], 'formats':'O int float int,int'.split()})
dt

dtype([('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [128]:
s = np.array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [129]:
type(s)

numpy.ndarray

In [130]:
s['Name']

array(['Smith', 'Jones'], dtype=object)

In [131]:
s['Height'].mean()

1.775

In [132]:
s[0]

('Smith', 45, 1.83, (0, 1))

In [133]:
s[1]['Age']

53

### Vectorization of Code



#### Basic Vectorization

In [134]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5

In [135]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [136]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [138]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [139]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [140]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [141]:
2 * r + 3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [142]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [143]:
r.shape

(4, 3)

In [144]:
s = np.arange(0, 12, 4)
s

array([0, 4, 8])

In [145]:
r + s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [146]:
s = np.arange(0, 12, 3)
s

array([0, 3, 6, 9])

In [147]:
r.transpose() + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [148]:
sr = s.reshape(-1, 1)
sr

array([[0],
       [3],
       [6],
       [9]])

In [149]:
sr.shape

(4, 1)

In [150]:
r + s.reshape(-1, 1)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [151]:
def f(x):
    return 3 * x + 5

In [152]:
f(0.5)

6.5

In [153]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

#### Memory Layout

In [154]:
x = np.random.standard_normal((1000000, 5))

In [155]:
y = 2 * x + 3

In [156]:
C = np.array((x, y), order='C')

In [157]:
F = np.array((x, y), order='F')

In [158]:
x = 0.0; y = 0.0

In [159]:
C[:2].round(2)

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ...,
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ...,
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])