구글 드라이브 불러오기

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
class HumanBeing(object):
    def __init__(self, first_name, eye_color):
        self.first_name = first_name
        self.eye_color = eye_color
        self.position = 0
    def walk_steps(self, steps):
        self.position += steps

In [9]:
Sandra = HumanBeing('Sandra', 'blue')

In [10]:
Sandra.first_name

'Sandra'

In [11]:
Sandra.position

0

In [12]:
Sandra.walk_steps(5)

In [13]:
Sandra.position

5

### A Look at Python Objects

#### int

In [14]:
n = 5

In [15]:
type(n)

int

In [16]:
n.numerator

5

In [17]:
n.bit_length()

3

In [18]:
n + n

10

In [19]:
2 * n

10

In [20]:
n.__sizeof__()

28

#### list

In [21]:
l = [1, 2, 3, 4]

In [22]:
type(l)

list

In [23]:
l.append(10)

In [24]:
l + l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [25]:
2 * l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [26]:
sum(l)

20

In [27]:
l.__sizeof__()

104

#### ndarray

In [28]:
import numpy as np

In [29]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
type(a)

numpy.ndarray

In [31]:
a.nbytes

128

In [32]:
a.sum()

120

In [33]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [34]:
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [35]:
2 * a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [36]:
sum(a)

array([24, 28, 32, 36])

In [37]:
np.sum(a)

120

In [38]:
a.__sizeof__()

112

#### DataFrame

In [39]:
import pandas as pd

In [45]:
df = pd.DataFrame(a, columns=list('abcd'))
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [41]:
type(df)

pandas.core.frame.DataFrame

In [42]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
df.sum()

a    24
b    28
c    32
d    36
dtype: int64

In [44]:
df.cumsum()

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [46]:
df + df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [47]:
2 * df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [49]:
np.sum(df)

a    24
b    28
c    32
d    36
dtype: int64

In [50]:
df.__sizeof__()

256

### Basics of Python Classes

In [51]:
class FinancialInstrument(object):
    pass

In [52]:
fi = FinancialInstrument()

In [53]:
type(fi)

__main__.FinancialInstrument

In [54]:
fi

In [55]:
fi.__str__()

'<__main__.FinancialInstrument object at 0x7fda5aa336a0>'

In [56]:
fi.price = 100
fi.price

100

In [57]:
class FinancialInstrument(object):
    author = 'Sunghan Kim'
    def __init__ (self, symbol, price):
        self.symbol = symbol
        self.price = price

In [58]:
FinancialInstrument.author

'Sunghan Kim'

In [59]:
aapl = FinancialInstrument('AAPL', 100)

In [60]:
aapl.symbol

'AAPL'

In [61]:
aapl.author

'Sunghan Kim'

In [62]:
aapl.price = 105
aapl.price

105

In [63]:
class FinancialInstrument(FinancialInstrument):
    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price = price

In [64]:
fi = FinancialInstrument('AAPL', 100)

In [65]:
fi.get_price()

100

In [67]:
fi.set_price(105)

In [68]:
fi.get_price()

105

In [69]:
fi.price

105

In [73]:
class FinancialInstrument(object):
    def __init__ (self, symbol, price):
        self.symbol = symbol
        self.__price = price
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [74]:
fi = FinancialInstrument('AAPL', 100)

In [75]:
fi.get_price()

100

In [77]:
fi._FinancialInstrument__price

100

In [78]:
fi._FinancialInstrument__price = 105

In [79]:
fi.set_price(100)

In [86]:
class PortfolioPosition(object):
    def __init__ (self, financial_instrument, position_size):
        self.position = financial_instrument
        self.__position_size = position_size
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size *  self.position.get_price()

In [87]:
pp = PortfolioPosition(fi, 10)

In [88]:
pp.get_position_size()

10

In [89]:
pp.get_position_value()

1000

In [90]:
pp.position.get_price()

100

In [92]:
pp.position.set_price(105)

In [93]:
pp.get_position_value()

1050

### Python Data Model

In [101]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z

In [102]:
v = Vector(1, 2, 3)
v

In [109]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

In [110]:
v = Vector(1, 2, 3)
v

Vector(1, 2, 3)

In [111]:
print(v)

Vector(1, 2, 3)


In [112]:
class Vector(Vector):
    def __abs__(self):
        return (self.x **2 + self.y ** 2 + self.z ** 2) ** 0.5
    def __bool__ (self):
        return bool(abs(self))

In [113]:
v = Vector(1, 2, -1)

In [114]:
abs(v) # abs : 절대값

2.449489742783178

In [115]:
bool(v)

True

In [116]:
v = Vector()
v

Vector(0, 0, 0)

In [117]:
abs(v)

0.0

In [118]:
bool(v)

False

In [119]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    
    def __mul__ (self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)

In [120]:
v = Vector(1, 2, 3)

In [121]:
v + Vector(2, 3, 4)

Vector(3, 5, 7)

In [122]:
v * 2

Vector(2, 4, 6)

In [124]:
class Vector(Vector):
    def __len__(self):
        return 3

    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [125]:
v = Vector(1, 2, 3)

In [126]:
len(v)

3

In [127]:
v[0]

1

In [128]:
v[-2]

2

In [129]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [130]:
v = Vector(1, 2, 3)

In [131]:
for i in range(3):
    print(v[i])

1
2
3


In [132]:
for coordinate in v:
    print(coordinate)

1
2
3


### The Vector Class

In [133]:
class Vector(object):
    def __init__ (self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z

    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

    def __abs__ (self):
        return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5
    
    def __bool__ (self):
        return bool(abs(self))

    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector (x, y, z)

    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)
    def __len__(self):
        return 3
    
    def _getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

     def __iter__(self):
        for i in range(len(self)):
            yield self[i]   