In [1]:
import numpy as np

In [4]:
np_array_a = np.array([1,2,3,4,5])
np_array_b = np.array([1., 2., 3., 4., 5.])

In [3]:
print (type(np_array_a))

<class 'numpy.ndarray'>


In [5]:
np_array_b.dtype

dtype('float64')

In [6]:
z = np.arange(10, dtype=np.float32)

In [8]:
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [9]:
z.shape

(10,)

In [11]:
z.ndim

1

In [12]:
from numpy import pi

In [13]:
pi_data = np.linspace(0, 1, 20)

In [14]:
pi_data

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [15]:
np.random.seed(123)

In [16]:
np.random.seed(12)
pi_data2 = np.random.random((20))
pi_data2

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496,
       0.91874701, 0.90071485, 0.03342143, 0.95694934, 0.13720932,
       0.28382835, 0.60608318, 0.94422514, 0.85273554, 0.00225923,
       0.52122603, 0.55203763, 0.48537741, 0.76813415, 0.16071675])

In [17]:
pi_data + pi_data2

array([0.15416284, 0.79268128, 0.36857817, 0.69163413, 0.22510128,
       1.1819049 , 1.21650433, 0.40184248, 1.37800197, 0.61089353,
       0.81014414, 1.18503055, 1.57580408, 1.53694607, 0.73910134,
       1.31069971, 1.3941429 , 1.38011426, 1.71550258, 1.16071675])

In [18]:
a = np.array([(1.3, 4, 5), (4,5,6)])

In [19]:
a.ndim

2

In [20]:
a.shape

(2, 3)

In [21]:
a.dtype

dtype('float64')

In [22]:
a2 = np.array([(1.3, 4, 5), (4,5,6)], dtype=np.float32)

In [23]:
a2

array([[1.3, 4. , 5. ],
       [4. , 5. , 6. ]], dtype=float32)

In [24]:
a2.dtype

dtype('float32')

In [25]:
b = np.array([[1, 7, 4, 5], [4,5,6,9]])

In [26]:
b.shape

(2, 4)

In [27]:
c = np.array([[1, 8, 4], [4,5,6], [4,5,6]])

In [28]:
c.shape

(3, 3)

In [29]:
c.ndim

2

In [30]:
a2.astype(np.int32)

array([[1, 4, 5],
       [4, 5, 6]])

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
tmp = np.ones((2,3,4), dtype=np.int32)

In [33]:
tmp.ndim

3

In [34]:
tmp

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [35]:
np.empty((6,34))

array([[1.02765670e-311, 1.02767929e-311, 6.04736351e-321,
                    nan, 3.82368604e-297, 3.82368605e-297,
        1.64290199e-287, 1.56108506e-282, 1.07669224e-282,
        1.42517535e-309, 5.11767337e-307, 1.07981234e+070,
        7.05154591e-278, 8.90557497e-308, 2.58082307e-263,
        1.39952050e-309, 5.85167001e-302, 2.38433293e-244,
        5.83663433e-309, 1.02215595e-234, 6.70824613e-230,
        1.65163777e-234, 3.82290735e-297, 3.83043487e-297,
        8.90070337e-308, 6.43323104e-220, 8.53043480e-254,
        1.50122859e-309, 8.10126907e-206, 2.40110410e-239,
        1.52295840e-309, 3.34301786e-186, 1.03126629e-229,
        6.75850675e-225],
       [1.53382319e-309, 1.43581525e-176, 1.03126629e-229,
        2.90275655e-215, 1.54468797e-309, 6.16677956e-167,
        1.24672444e-205, 1.55555276e-309, 2.64861166e-157,
        5.35464071e-196, 1.56641754e-309, 1.13757005e-147,
        2.29980067e-186, 1.58271463e-309, 4.48006638e-307,
        9.42855658e-129, 4.044

In [36]:
d = np.arange(12)

In [37]:
d2 = d.reshape(2,6)

In [38]:
d2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [39]:
f = np.arange(48)

In [40]:
f2 = f.reshape(3,4,4)

In [41]:
f2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [42]:
a = np.arange(10)

In [43]:
tmp2 = []
for x in range(10):
    tmp2.append(x * 10)

In [44]:
b = np.arange(12)

In [45]:
b-a

ValueError: operands could not be broadcast together with shapes (12,) (10,) 

In [46]:
a - b

ValueError: operands could not be broadcast together with shapes (10,) (12,) 

In [47]:
b = np.arange(10)

In [48]:
a - b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
pi_data.reshape(4,5)

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [50]:
pi_data2.reshape(4,5)

array([[0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496],
       [0.91874701, 0.90071485, 0.03342143, 0.95694934, 0.13720932],
       [0.28382835, 0.60608318, 0.94422514, 0.85273554, 0.00225923],
       [0.52122603, 0.55203763, 0.48537741, 0.76813415, 0.16071675]])

In [51]:
pi_data.reshape(4,5) + pi_data2.reshape(4,5)

array([[0.15416284, 0.79268128, 0.36857817, 0.69163413, 0.22510128],
       [1.1819049 , 1.21650433, 0.40184248, 1.37800197, 0.61089353],
       [0.81014414, 1.18503055, 1.57580408, 1.53694607, 0.73910134],
       [1.31069971, 1.3941429 , 1.38011426, 1.71550258, 1.16071675]])