In [2]:
import numpy as np

In [3]:
x = np.arange(0, 10, 1)
y = x ** 2
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [4]:
np.savez("x_y-squared.npz", x_axis=x, y_axis=y)

In [5]:
del x, y

In [6]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os         module    <module 'os' from 'C:\\Us<...>\\anaconda3\\lib\\os.py'>
sys        module    <module 'sys' (built-in)>


In [7]:
load_xy = np.load("x_y-squared.npz")

print(load_xy.files)

['x_axis', 'y_axis']


In [8]:
whos

Variable   Type       Data/Info
-------------------------------
load_xy    NpzFile    <numpy.lib.npyio.NpzFile <...>ct at 0x000001250B8F9E80>
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os         module     <module 'os' from 'C:\\Us<...>\\anaconda3\\lib\\os.py'>
sys        module     <module 'sys' (built-in)>


In [9]:
x = load_xy["x_axis"]
y = load_xy["y_axis"]
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [10]:
array_out = np.block([x[:, np.newaxis], y[:, np.newaxis]])
print("the output array has shape ", array_out.shape, " with values:")
print(array_out)

the output array has shape  (10, 2)  with values:
[[ 0  0]
 [ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]
 [ 6 36]
 [ 7 49]
 [ 8 64]
 [ 9 81]]


In [11]:
np.savetxt("x_y-squared.csv", X=array_out, header="x, y", delimiter=",")

In [12]:
del x, y

In [13]:
load_xy = np.loadtxt("x_y-squared.csv", delimiter=",")

In [14]:
load_xy.shape

(10, 2)

In [15]:
x = load_xy[:, 0]
y = load_xy[:, 1]
print(x)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
